version: '3.8'
services:
  api:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm run start"
    depends_on:
      - postgres
  postgres:
    image: 'bitnami/postgresql'
    container_name: btc-db
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=btc
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
